name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Debug - Show Next.js config
        run: cat next.config.js

      - name: Debug - Show package.json scripts
        run: grep -A 10 '"scripts"' package.json

      - name: Build
        run: npm run build
        
      - name: Check output directory
        run: |
          if [ -d "out" ]; then
            echo "Build successful - out directory exists"
            ls -la out
          else
            echo "Build failed - out directory does not exist"
            echo "Checking all directories:"
            find . -maxdepth 2 -type d
            exit 1
          fi

      - name: Create out directory if it doesn't exist
        run: mkdir -p out

      - name: Create .nojekyll file
        run: touch out/.nojekyll

      - name: List output contents
        run: ls -la out

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          token: ${{ secrets.PAT }}
          force: true
